spring:
  application:
    name: otp
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  redis:
    port: 6380
    host: localhost
    timeout: 10s
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8020
# untuk eureka service registry
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com:
      irfaan:
        microservice:
          otp: debug
