version: "3"
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
    - "6379:6379"
    volumes:
    - "redis:/data"
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ahmadirfaan
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: account
    volumes:
    - "mypostgres:/var/lib/postgresql/data/" #persist data event
    ports:
    - "5432:5432"
#  mysql:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'db'
#      #ini untuk mendefinisikan user bisa pake root atau tidak
#      MYSQL_USER: ahmadirfaan
#      #mendefiniskan password user
#      MYSQL_PASSWORD: P@ssw0rd
#      #password untuk root password
#      MYSQL_ROOT_PASSWORD: P@ssw0rd
#    ports:
#    - '3306:3306'
#    expose:
#      - '3306'
#    volumes:
#    - my-db:/var/lib/mysql
volumes:
  mydb:
  redis:
  mypostgres: