spring:
  application:
    name: account
  zipkin:
    enabled: true
    base-url: http://localhost:9411/
  redis:
    host: localhost # setting untuk redis
    port: 6380
  datasource:
    url: jdbc:postgresql://localhost:5433/account
    username: postgres
    password: P@ssw0rd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default-schema: public
        format_sql: true
  sql:
    init:
      platform: hibernate.dialect.PostgreSQLDialect
server:
  port: 8010
#eureka atau load balancer setting
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
# logging untuk level project-nya
logging:
  level:
    com:
      irfaan:
        microservicesaccount: debug
# zipkin setting

