spring:
  application:
    name: email
## email config
  mail:
    port: 587
    host: smtp.gmail.com
    username: ${USERNAME_EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
    protocol: smtp

  # connection redis
  redis:
    port: 6380
    host: localhost
    timeout: 10s
logging:
  level:
    com:
      irfaan:
        microservices:
          emailservice: debug
server:
  port: 8030